// <auto-generated />
using System;
using BackEndCapstone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEndCapstone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200205181230_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEndCapstone.Models.Gemstone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gemstone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "amazonite mineral rock was treasured by the ancient egyptians who made beautiful jewelry, ornamental pieces and carved important texts into this stone. amazonite has always been prized for its beauty and healing power. this pale green mineral rock is believed to date back as far as the 10th century bc.amazonite is usually pale green, but can sometimes be blue-green, turquoise or yellow-green and can also have white streaks. the color of amazonite is due to the presence of lead within the stone and color variation may exist within a single stone.",
                            ImagePath = "Amazonite.gif",
                            Title = "Amazonite"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Calcite, also called limespar, is a very common rock-forming mineral. The word calcite comes from the Latin calx and the Greek chalix, which means lime. Calcite has more uses than almost any other mineral. A great deal of calcite is formed from the shells of dead marine organisms. Calcite may also be found in volcanic or mantle-derived rocks. A relatively soft stone, calcite has a Mohs hardness of 3. Calcite is transparent to translucent and may occasionally show phosphorescence or fluorescence.Because of its understated coloring, yellow calcite matches up nicely with antiqued gold-plated brass. It can be a grounding for more flamboyant colors such as carnelian.  ",
                            ImagePath = "cacite.jpg",
                            Title = "Calcite"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Blue lace agate is a type of variegated chalcedony, more specifically a variety of quartz. This type of agate is most notably recognized by its predominantly light blue banded layers that have also been known to include bright blue, white and brown hues. Agates typically form as nodules or geodes in igneous rocks.The soft hue of blue lace agate pairs exceptionally well with other pastel-colored gemstones. Looking at the bands of color, pair your blue lace agate with the tones of the bands to draw increased attention to the swirling pattern. For a complementary color pairing, blue lace agate provides a great base to draw attention to orange/red gemstones such as carnelian, sunstone, amber and other forms of agate or banded jaspers.",
                            ImagePath = "blueLace.gif",
                            Title = "Blue Lace Agate"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Coral has been called the 'garden of the sea' because it was once believed to be a plant. Instead, coral belongs to a small, but important group of organic gemstones. Coral is formed through a biological process rather than being a mineral with a crystalline structure like most colored stones. Precious coral is a deep water coral that forms in rocky seabeds with low levels of sedimentation, typically in dark environments over 500-feet deep. Coral is very sensitive to acid and heat. Coral's color is known to fade with wear and tear. To prevent color loss, avoid exposing coral to direct sunlight for prolonged periods of time and avoid temperature extremes.",
                            ImagePath = "coral.jpg",
                            Title = "Petrified Coral"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Onyx is a form of chalcedony, which is a microcrystalline quartz formed in the gas cavities of lava. Its multi-layered structure is similar to that of agates. When the stone has a black base and a white upper layer, it's called onyx. (Black onyx is uniformly black chalcedony. Much of what is referred to as 'black onyx' is gray chalcedony that has been chemically treated to be a rich black. Black is neutral, making it a great design element to combine with many different colored stones, other gemstone beads and all metal tones. Its deep, dark, lustrous surface can play a striking contrast to the warm-colored gemstones like garnet, carnelian and coral.) ",
                            ImagePath = "blackOnyx.jpg",
                            Title = "Black Onyx"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lapis lazuli is one of the oldest opaque gemstones in history--more than 6,500 years! This deep blue stone includes tiny flecks of mica, like a night sky full of stars. Its most well-known source is deep in the mountains of modern Afghanistan. Lapis lazuli is an intensely blue stone made of a deep blue lazurite, cloudy white calcite, sparkly pyrite and other minerals. This beautiful mixture of textures gives lapis lazuli its characteristic look.Lapis lazuli is found with limestone or as separate boulders. Stones from what is now modern Afghanistan and Pakistan are still considered to be of the best quality. Royal blue lapis lazuli characteristically has either whitish or yellowish matrix or feathering. When it is flecked with white, it is perfectly complemented by silver and turquoise for a Southwestern look. If it has brassy specks, it is regal with gold. Lapis also has darker regions that can be accented when strung with black onyx or antiqued silver beads. ",
                            ImagePath = "lapis.jpg",
                            Title = "Lapis Lazuli"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Larimar is a rare blue variety of pectolite. The serene blue color results from the substitution of cobalt for calcium in the stone and varies from white and light-blue to green-blue and deep blue or 'volcanic blue.' With swirling bands of white, larimar mimics the wave crests of crystal blue Caribbean waters.To date, the only known major deposits of larimar are found in the Dominican Republic where it was most likely treasured by the area's first inhabitants, the Taino Indians. Many jewelry artists incorporate polished freeform larimar pendants and cabochons into necklaces and create earrings with larimar rounds and chips. Freeform larimar stones can be used in wire-wrapped designs such as necklaces, rings, bracelets and earrings.",
                            ImagePath = "larimar.jpg",
                            Title = "Larimar"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sunstone began as a costly and little-known gemstone until deposits were found in Norway and Siberia. This gemstone has a special history in the United States, however, where sunstone varieties called 'heliolite' have been mined in Oregon. Sunstone gems belong to the feldspar group, which encompasses a large variety of gemstone materials--including moonstone and amazonite. The sparkly metallic glitter in this particular feldspar is called aventurescence, which is caused by flat, reflective inclusions (sometimes called 'schiller'). These inclusions can be hematite, copper or other minerals. Larger inclusions tend to be more glittery while small inclusions create a red or gold sheen on top of the stone's natural color. Sunstone, with its rich, earthy red-orange tones, works great in settings of all metal tones. You can't go wrong pairing sunstone with silver, gold, rose gold, copper or other metals. Pair with moonstone to draw attention to the schiller flash in both of these feldspar minerals. Create a complementary color scheme for high contrast and drama by pairing sunstone with emerald green and lapis lazuli blue ",
                            ImagePath = "sunstone.jpg",
                            Title = "Sunstone"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lepidolite is mined as a source of the element lithium along with other rare earth elements such as cesium and rubidium. Lepidolite is an important source of lithium, which is the lightest metal in the world. Lepidolite is a translucent to transparent rose to purple colored phyllosilicate mineral of the mica group. Lepidolite is associated with other lithium-bearing minerals like spodumene in pegmatite bodies. It is one of the major sources of the rare alkali metals rubidium and cesium. It is found most often as small, scaly crystals in dense aggregates. It is also found in masses and groupings such as foliated, flaky and scaly forms.With its variety of hues from pinkish rose to purple along with other shades, lepidolite offers more tonal flexibility that you might think at first glance. For a slight contrast, consider pairing lepidolite with the lighter rose quartz. ",
                            ImagePath = "Lepidolite.jpg",
                            Title = "Lepidolite"
                        },
                        new
                        {
                            Id = 10,
                            Description = " Quartz includes a large group of minerals based on silicon dioxide. Rose quartz is a macrocrystalline form, as are amethyst, aventurine and citrine. It is a milky pink color, often crackled, and found mainly in large clumps. Only rarely is it found in single crystal form. It is believed that the pink color is due to a small amount of titanium.Rose quartz is found in pegmatite, a course-grained igneous rock (usually granite). Transparent rose quartz is rare, but is found where the best material comes from: Madagascar.Rose quartz is typically a cloudy translucent pink or slightly peach color. The violet of amethyst, either light or dark, is close to pink on the color wheel, and makes for a lovely two-color scheme set in silver. For a beautifully cool split-complementary color scheme, match rose quartz with grass-green peridot and frosty blue-green amazonite.",
                            ImagePath = "roseQuartz.jpg",
                            Title = "Rose Quartz"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Opals come in three natural varieties: opalescent precious opal, fire opal (yellow to red-orange) and the generally opaque common opal. A French manufacturer, Gilson, created the first 'opalescent' imitation opal in 1973 though synthetic opals have been created since the '30s. Natural opals are non-crystalline, hydrated silicon dioxide gemstones that contain up to 30% water. It's possible for opals to dry out and crack, and they are relatively soft, fragile gemstones. Precious opals display a unique opalescence. Depending on the angle of view, rainbow-like flashes of different colors appear, caused by light reflecting off of extremely small spheres of cristobalite within the silica gel. The phenomenon is called interference. The flashing of color is often referred to as 'fire' or 'play of light.' Precious opals appear in a range of white to black (usually dark gray, green or blue backgrounds).",
                            ImagePath = "opal2.jpg",
                            Title = "Opal"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Jasper, an opaque chalcedony, comes in a wide variety of colors, each with unique patterning. Autumn jasper is the variety of jasper known for its mottled warm brick red and avocado green appearance. The term 'jasper' itself comes from the Greek work iaspi, which means 'spotted stone.' Jasper gemstones are found all over the world, but raw autumn jasper materials are often found in India, Madagascar and South Africa.  ",
                            ImagePath = "autumnJasper.jpg",
                            Title = "Autumn Jasper"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The unique artistry of Jasper is that of Nature itself - golden sunshine, a nighttime sky, poppy fields or a deep green forest, desert sands, the undulating ocean, red rock canyons, sweeping mountains. Each stone is a masterpiece of the Creator, bold and primitive in style, solid and earthy in form, with a warm, harmonious energy that resonates with the primal self.There is a wide variety of Jaspers, characterized by color, form, and similarities to places or animals found in nature. Many are named for the regions where they are mined; others are named by those who discovered them. Though far too extensive to cover here, we will mention a few of the more popular and familiar Jaspers, some with their own pages and additional metaphysical properties. Multi-colored Jasper carries the properties of its dominant color, or colors, while still drawing energies from its subtle hues.",
                            ImagePath = "jasper.jpg",
                            Title = "Jasper"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Pearls are one of a few natural or organic gemstones (others include coral, amber, jet and mother-of-pearl). Produced by the pearl oyster and the freshwater pearl mussel, natural pearls are a small irritant within the oyster or mussel which has been coated with nacre to reduce that irritation. Pearls created by a pearl farmer, who inserts a tiny piece, or 'seed' of mother-of-pearl into a freshwater pearl oyster. The pearl oyster will coat the seed with progressive layers of nacre, creating a pearl. Tennessee has been the leading state for cultured freshwater pearl production since the 1960s.",
                            ImagePath = "pearl.jpg",
                            Title = "Pearl"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Aqua Aura Quartz is a beautiful bright blue quartz crystal created from the result of a special process involving gold. The crystals are heated and fine vaporized gold is bonded to the crystal’s surface. It is considered by many to have a high vibration and to aid communication and psychic skills.",
                            ImagePath = "aquaqtz.jpg",
                            Title = "Aqua Quartz"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Wood is generally easy to find and work with so wherever wood is found you will find wooden beads. Regional carpenters and carvers use the most readily available species of wood and beadmaking itself was used as exercises for apprentices or as spare time work for journeymen or masters. This wide variety of woodworkers and woods makes for an astonishing variety of forms, sizes, and types of wood beads.Many species of treesprovide material for wood beads. These include olive, sandalwood,bamboo, bayong, ebony, ironwood, palm, apple, pear, and rose, to namebut a few. All of these types of wood have been used for beads eitherbecause the grain of the wood is beautiful or because the wood isaromatic.",
                            ImagePath = "Wood.jpg",
                            Title = "Wood"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Mother-of-pearl shell for jewelry refers to the nacre that coats the inside layer of the mollusk shell which is used to form pearls--hence, it's the mother of the pearl. Mother-of-pearl shell jewelry can include much larger focal pieces than simple pearls since nacre substance takes up a whole shell's interior, offering a larger working surface for carving. The pearly luster of mother-of-pearl shell, called orient comes from an overlap of aragonite platelets under a skin of conchiolin (an organic substance). Mother-of-pearl shell offers a feminine iridescence that mixes beautifully with the shell beads. Natural mother-of-pearl shell is not bleached, making it a popular choice among the ecologically minded.",
                            ImagePath = "MotherOfPearl.jpg",
                            Title = "Mother Of Pearl"
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 687, DateTimeKind.Local).AddTicks(113),
                            Description = "Rustic triangle shaped copper earrings with large, round calcite gemstone.",
                            ImagePath = "TriangleCalciteEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Calcite Triangle Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(3919),
                            Description = "Elegant sterling silver and black onyx dangle earrings.",
                            ImagePath = "BlackOnyxDangle.jpg",
                            ProductTypeId = 1,
                            Title = "Black Onyx Dangle Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4036),
                            Description = "Trendy tassle earrings with all natural pink and coral jasper gemstones.",
                            ImagePath = "blueJasperTassle.jpg",
                            ProductTypeId = 1,
                            Title = "Pink and Blue Jasper Tassle Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4073),
                            Description = "Hammered out gold hoop earrings with wire-wrapped lepidolite chips.",
                            ImagePath = "LepidoliteChipHoops.jpg",
                            ProductTypeId = 1,
                            Title = "Lepidolite Gold Hoops",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4102),
                            Description = "Hammered out gold hoops with wire wrapped pieces of petrified coral.",
                            ImagePath = "coralHoops.jpg",
                            ProductTypeId = 1,
                            Title = "Gold Hoop Earrings With Petrified Coral",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4133),
                            Description = "Hammered out gold earrings with bronze chain.",
                            ImagePath = "GoldBronzeChainEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Gold and Bronze Chain Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4159),
                            Description = "Teardrop shaped gold earrings with black tassles.",
                            ImagePath = "GoldTeardropBlackTassle.jpg",
                            ProductTypeId = 1,
                            Title = "Teardrop Black Tassle Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4185),
                            Description = "Hammered out diamond shaped gold hoops with wire wrapped larimar gemstones.",
                            ImagePath = "DiamondLarimarEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Diamond Shaped Hoops with Larimar Gemstones",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4211),
                            Description = "Asymmetrical sterling silver bead frames with rare cut amazonite gemstones.",
                            ImagePath = "SterlingAmazoniteEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Sterling Silver and Amazonite Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4239),
                            Description = "Hammered out copper hoop earrings with wire wrapped pink opal gemstones.",
                            ImagePath = "BronzePinkOpalHoops.jpg",
                            ProductTypeId = 1,
                            Title = "Copper Hoops with Pink Opal",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4314),
                            Description = "Rare cut autumn jasper gemstones set inside sterling silver bead frame.",
                            ImagePath = "AutumnJasperFramed.jpg",
                            ProductTypeId = 1,
                            Title = "Framed Autumn Jasper Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4343),
                            Description = "Hammered out gold hoop earrings wire wrapped with chips of blue lace agate.",
                            ImagePath = "BlueLaceHoops.jpg",
                            ProductTypeId = 1,
                            Title = "Gold Hoops with Blue Lace Agate",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 13,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4369),
                            Description = "Inverted gold teardrop earrings with wire wrapped lepidolite gemstones.",
                            ImagePath = "InvertedTeardropLarimar.jpg",
                            ProductTypeId = 1,
                            Title = "Inverted Teardop Lepidolite Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 14,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4396),
                            Description = "Gold hoop earrings accented with wire wrapped, teardrop shaped lapis gemstone.",
                            ImagePath = "LapisHoopEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Gold Hoop Lapis Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 15,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4422),
                            Description = "Hammered out gold teardrop earrings with wire wrapped chips of rose quartz.",
                            ImagePath = "RoseGoldTeardrop.jpg",
                            ProductTypeId = 1,
                            Title = "Gold Teardrop Earrings with Rose Quartz",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 16,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4448),
                            Description = "Hammered out gold hoop earrings with rare cut aqua quartz gemstones.",
                            ImagePath = "AquaQuartzGoldHoops.jpg",
                            ProductTypeId = 1,
                            Title = "Gold Hoop earrings with Aqua Quartz Gemstone",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 17,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4475),
                            Description = "Beautiful antique copper earrings with shimmering sunstones.",
                            ImagePath = "sunstoneEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Antique Copper Earrings With Sunstone",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 18,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4503),
                            Description = "Bronze dangle earrings with unique cut autumn jasper gemstones.",
                            ImagePath = "BronzeAndAutumnJasper.jpg",
                            ProductTypeId = 1,
                            Title = "Bronze and Autumn Jasper Dangle Earrings ",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 19,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4529),
                            Description = "Beautifully elegant sterling silver thread earrings with freshwater pearls.",
                            ImagePath = "PearlThreadEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Threaded Pearl Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 20,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4556),
                            Description = "Hammered out gold earrings with wire wrapped freswater pearls.",
                            ImagePath = "HammeredGoldPearl.jpg",
                            ProductTypeId = 1,
                            Title = "Gold Earrings with Wire Wrapped Pearls",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 21,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4582),
                            Description = "Bronze hoop earrings with pink and grey jasper gemstones.",
                            ImagePath = "PinkGreyJasperEarrings.jpg",
                            ProductTypeId = 1,
                            Title = "Pink and Grey Jasper Earrings",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 22,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4608),
                            Description = "Delicate pink freshwater pearl necklace on gold chain.",
                            ImagePath = "pearlNecklace.jpg",
                            ProductTypeId = 2,
                            Title = "Delicate Freshwater Pearl Necklace",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 23,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4633),
                            Description = "Beautiful threaded freshwater pearl necklace with aqua quartz and purple crystals.",
                            ImagePath = "ThreadPearlNecklace.jpg",
                            ProductTypeId = 2,
                            Title = "Threaded Pearl Necklace",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 24,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4658),
                            Description = "Fun earth toned bracelet made with glass beads and jasper gemstones.",
                            ImagePath = "JasperBracelet.jpg",
                            ProductTypeId = 3,
                            Title = "Jasper and Glass Bracelet",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 25,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4684),
                            Description = "Bracelet made with wooden beads and stretchy floss cord.",
                            ImagePath = "LightWoodBracelet.jpg",
                            ProductTypeId = 3,
                            Title = "Light Wood Bracelet",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 26,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(4710),
                            Description = "Bracelet made with wooden beads and stretchy floss cord.",
                            ImagePath = "DarkWoodBracelet.jpg",
                            ProductTypeId = 3,
                            Title = "Dark Wood Bracelet",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.ProductGemstone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GemstoneId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductGemstone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GemstoneId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            GemstoneId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            GemstoneId = 13,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            GemstoneId = 9,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            GemstoneId = 4,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            GemstoneId = 7,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 7,
                            GemstoneId = 1,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 8,
                            GemstoneId = 11,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 9,
                            GemstoneId = 12,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 10,
                            GemstoneId = 3,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 11,
                            GemstoneId = 9,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 12,
                            GemstoneId = 6,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 13,
                            GemstoneId = 10,
                            ProductId = 15
                        },
                        new
                        {
                            Id = 14,
                            GemstoneId = 15,
                            ProductId = 16
                        },
                        new
                        {
                            Id = 15,
                            GemstoneId = 8,
                            ProductId = 17
                        },
                        new
                        {
                            Id = 16,
                            GemstoneId = 12,
                            ProductId = 18
                        },
                        new
                        {
                            Id = 17,
                            GemstoneId = 14,
                            ProductId = 19
                        },
                        new
                        {
                            Id = 18,
                            GemstoneId = 14,
                            ProductId = 20
                        },
                        new
                        {
                            Id = 19,
                            GemstoneId = 13,
                            ProductId = 21
                        },
                        new
                        {
                            Id = 20,
                            GemstoneId = 14,
                            ProductId = 22
                        },
                        new
                        {
                            Id = 21,
                            GemstoneId = 14,
                            ProductId = 23
                        },
                        new
                        {
                            Id = 22,
                            GemstoneId = 13,
                            ProductId = 24
                        },
                        new
                        {
                            Id = 23,
                            GemstoneId = 16,
                            ProductId = 25
                        },
                        new
                        {
                            Id = 24,
                            GemstoneId = 16,
                            ProductId = 26
                        },
                        new
                        {
                            Id = 25,
                            GemstoneId = 17,
                            ProductId = 23
                        },
                        new
                        {
                            Id = 26,
                            GemstoneId = 15,
                            ProductId = 23
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "These are so pretty! love the color!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(6968),
                            ProductId = 3,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Love these gemstones and the shape of the hoops",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(7762),
                            ProductId = 15,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Lapis gems are my favorite. Nice wire wrapping!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(7832),
                            ProductId = 14,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "These purple gems are so cool. such a pretty design!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(7861),
                            ProductId = 13,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Didn't know quartz came in this color. Very cool!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(7886),
                            ProductId = 16,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "These sunstones are so pretty!!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(7914),
                            ProductId = 17,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "These blue lace gems are awesome. Love the wire wrapping",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(7938),
                            ProductId = 12,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Interesting earrings!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8035),
                            ProductId = 11,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "These bead frames are cool!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8062),
                            ProductId = 11,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Oh my god these are so pretty! I want a pair",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8089),
                            ProductId = 10,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 11,
                            Comment = "I like how you used the bronze cirle with the gemstones!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8113),
                            ProductId = 18,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Threaded earrings are so pretty. do you have them in any other gemstone?",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8137),
                            ProductId = 19,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 13,
                            Comment = "I love how you got the pearls to alternate up and down!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8162),
                            ProductId = 20,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 14,
                            Comment = "These pearls are so pretty!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8186),
                            ProductId = 22,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Ordered this necklace and i absolutely love it. Would definitely recommend it!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8210),
                            ProductId = 22,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 16,
                            Comment = "I love the antique feel of these earrings!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8235),
                            ProductId = 2,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Nice wire wrapping!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8258),
                            ProductId = 4,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 18,
                            Comment = "I love the antique feel of these earrings!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8284),
                            ProductId = 2,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 19,
                            Comment = "So cute and trendy!",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8308),
                            ProductId = 7,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Ordered a few of these and I love them.",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8333),
                            ProductId = 25,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 21,
                            Comment = "This bracelet is dope",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 689, DateTimeKind.Local).AddTicks(8357),
                            ProductId = 26,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.ProductTutorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TutorialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductTutorial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 3,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 3,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 5,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 8,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 10,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 16,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 17,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 18,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 21,
                            TutorialId = 2
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 21,
                            TutorialId = 2
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Earrings"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Necklaces"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bracelets"
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.Tutorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tutorial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(636),
                            Description = "First feed one crimp beed onto the wire and then loop it through a clasp or a jump ringand then back through the crimp. PLace the crimp in the OUTER jaw of the crimp tool and make one firm compression. Then place the crimp bead into the crescent-shaped groove of the crimp tool and firmly compress. String the remaining beads onto the wire.",
                            ProductId = 0,
                            Title = "How to use crimping pliers",
                            VideoPath = "CrimpTutorial.mp4"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(1455),
                            Description = "In this video, learn how to make a wrapped wire loop for jewelry making. This basic technique is used when putting a bead on a head pin or eye pin as a dangle or a link, and is more durable than a simple wire loop.",
                            ProductId = 0,
                            Title = "How to wire wrap loops for earrings",
                            VideoPath = "WireWrappedLoopForEarrings.mp4"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(1528),
                            Description = "This video shows you how to use all the essential jewelry making tools for beginners.",
                            ProductId = 0,
                            Title = "Tools for beginners",
                            VideoPath = "Tools101.mp4"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(1558),
                            Description = "Learn how to make that trickey wire wrapped bead cap with this video.",
                            ProductId = 0,
                            Title = "How to Make a Wire Wrapped Bead Cap",
                            VideoPath = "WireBeadCaps.mp4"
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.TutorialReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("TutorialId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TutorialReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Thanks for posting. I struggled with making good looking crimps for so long. This video was very helpful.",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(4154),
                            TutorialId = 1,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Glad you posted this. I just started making jewelry and wasn't sure which tools to buy! thanks again.",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(5213),
                            TutorialId = 3,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "My wire wrapping always looks so ugly because i was doing it wrong. Glad you posted this",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(5319),
                            TutorialId = 2,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "My wire wrapping looks so much better after watching this video! thank you",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(5367),
                            TutorialId = 2,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "I've had a hard time with bead caps for a while, hoping that after seeing this video it wont be as difficult",
                            DateAdded = new DateTime(2020, 2, 5, 12, 12, 29, 690, DateTimeKind.Local).AddTicks(5406),
                            TutorialId = 4,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BackEndCapstone.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "00000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22bfb3df-e202-49b2-9310-778e191c4474",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEA6vBRNFnOxmbSMkZk60dXt4BQSqUhs+yogWiar2rncNzrXpZWigN0ZQvnBW0+FezQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com",
                            FirstName = "admin",
                            LastName = "admin"
                        },
                        new
                        {
                            Id = "10000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7784c348-a7fa-4b95-9479-e611a3bd5fa0",
                            Email = "aryn@aryn.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARYN@ARYN.COM",
                            NormalizedUserName = "ARYN@ARYN.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "aryn@aryn.com",
                            FirstName = "aryn",
                            LastName = "weatherly"
                        },
                        new
                        {
                            Id = "01000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0af8af63-dcf3-44df-985b-5adb0eae8b90",
                            Email = "sage@sage.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SAGE@SAGE.COM",
                            NormalizedUserName = "SAGE@SAGE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "sage@sage.com",
                            FirstName = "sage",
                            LastName = "klein"
                        },
                        new
                        {
                            Id = "00100000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4cb1d16-d4c7-4f89-a3fb-ebbd0b9e73fc",
                            Email = "heidi@heidi.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HEIDI@HEIDI.COM",
                            NormalizedUserName = "HEIDI@HEIDI.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "heidi@heidi.com",
                            FirstName = "heidi",
                            LastName = "smith"
                        },
                        new
                        {
                            Id = "00010000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ce4f18b-2a94-47f7-abc9-bfde8078cc0a",
                            Email = "lauren@lauren.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAUREN@LAUREN.COM",
                            NormalizedUserName = "LAUREN@LAUREN.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "lauren@lauren.com",
                            FirstName = "Lauren",
                            LastName = "Maxwell"
                        },
                        new
                        {
                            Id = "00001000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c27a6440-d6a1-4976-8910-c7e317a6b0cb",
                            Email = "dylan@dylan.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DYLAN@DYLAN.COM",
                            NormalizedUserName = "DYLAN@DYLAN.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "dylan@dylan.com",
                            FirstName = "Dylan",
                            LastName = "Griffin"
                        },
                        new
                        {
                            Id = "000001000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd37bcbd-1069-417e-875b-fa044a1fabe0",
                            Email = "madi@madi.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MADI@MADI.COM",
                            NormalizedUserName = "MADI@MADI.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "madi@madi.com",
                            FirstName = "madi",
                            LastName = "peper"
                        },
                        new
                        {
                            Id = "000000010-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "013f8687-0d7d-4911-9e74-96d5ba60ec31",
                            Email = "mo@mo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MO@MO.COM",
                            NormalizedUserName = "MO@MO.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "mo@mo.com",
                            FirstName = "mo",
                            LastName = "silvera"
                        },
                        new
                        {
                            Id = "000000001-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3e45df2-f35e-4c19-be92-94a4c72f5a7a",
                            Email = "taylor@taylor.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TAYLOR@TAYLOR.COM",
                            NormalizedUserName = "TAYLOR@TAYLOR.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "taylor@taylor.com",
                            FirstName = "taylor",
                            LastName = "caroll"
                        });
                });

            modelBuilder.Entity("BackEndCapstone.Models.Product", b =>
                {
                    b.HasOne("BackEndCapstone.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndCapstone.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
